query factories($block: Block_height, $where: Factory_filter, $orderBy: Factory_orderBy, $orderDirection: OrderDirection, $first: Int, $skip: Int){
    factories(block: $block, where: $where, orderBy: $orderBy, orderDirection: $orderDirection, first: $first, skip: $skip){
        id
        poolCount
        txCount
        totalVolumeUSD
        totalVolumeETH
        totalFeesUSD
        totalFeesETH
        untrackedVolumeUSD
        totalValueLockedUSD
        totalValueLockedETH
        totalValueLockedUSDUntracked
        totalValueLockedETHUntracked
        owner
    }
}