query flash($id: ID!, $block: Block_height){
    flash(id: $id, block: $block){
        id
        transaction{
            id
            blockNumber
            timestamp
            gasUsed
            gasPrice
        }
        timestamp
        pool{
            id
            createdAtTimestamp
            createdAtBlockNumber
            feeTier
            liquidity
            sqrtPrice
            feeGrowthGlobal0X128
            feeGrowthGlobal1X128
            token0Price
            token1Price
            tick
            observationIndex
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            totalValueLockedToken0
            totalValueLockedToken1
            totalValueLockedETH
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            liquidityProviderCount
        }
        sender
        recipient
        amount0
        amount1
        amountUSD
        amount0Paid
        amount1Paid
        logIndex
    }
}