query increaseEvents($block: Block_height, $orderBy: IncreaseEvent_orderBy, $orderDirection: OrderDirection, $first: Int, $skip: Int){
    increaseEvents(block: $block, orderBy: $orderBy, orderDirection: $orderDirection, first: $first, skip: $skip){
        id
        pool{
            id
            createdAtTimestamp
            createdAtBlockNumber
            feeTier
            liquidity
            sqrtPrice
            feeGrowthGlobal0X128
            feeGrowthGlobal1X128
            token0Price
            token1Price
            tick
            observationIndex
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            totalValueLockedToken0
            totalValueLockedToken1
            totalValueLockedETH
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            liquidityProviderCount
        }
        tokenID
        position{
            id
            owner
            liquidity
            depositedToken0
            depositedToken1
            withdrawnToken0
            withdrawnToken1
            collectedToken0
            collectedToken1
            collectedFeesToken0
            collectedFeesToken1
            amountDepositedUSD
            amountWithdrawnUSD
            amountCollectedUSD
            feeGrowthInside0LastX128
            feeGrowthInside1LastX128
        }
        amount0
        amount1
        token0{
            id
            symbol
            name
            decimals
            totalSupply
            volume
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            poolCount
            totalValueLocked
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            derivedETH
        }
        token1{
            id
            symbol
            name
            decimals
            totalSupply
            volume
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            poolCount
            totalValueLocked
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            derivedETH
        }
        timeStamp
        transaction{
            id
            blockNumber
            timestamp
            gasUsed
            gasPrice
        }
    }
}