query poolDayDatas($block: Block_height, $where: PoolDayData_filter, $orderBy: PoolDayData_orderBy, $orderDirection: OrderDirection, $first: Int, $skip: Int){
    poolDayDatas(block: $block, where: $where, orderBy: $orderBy, orderDirection: $orderDirection, first: $first, skip: $skip){
        id
        date
        pool{
            id
            createdAtTimestamp
            createdAtBlockNumber
            feeTier
            liquidity
            sqrtPrice
            feeGrowthGlobal0X128
            feeGrowthGlobal1X128
            token0Price
            token1Price
            tick
            observationIndex
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            totalValueLockedToken0
            totalValueLockedToken1
            totalValueLockedETH
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            liquidityProviderCount
        }
        liquidity
        sqrtPrice
        token0Price
        token1Price
        tick
        feeGrowthGlobal0X128
        feeGrowthGlobal1X128
        tvlUSD
        volumeToken0
        volumeToken1
        volumeUSD
        feesUSD
        txCount
        open
        high
        low
        close
    }
}