query pools($block: Block_height, $where: Pool_filter, $orderBy: Pool_orderBy, $orderDirection: OrderDirection, $first: Int, $skip: Int){
    pools(block: $block, where: $where, orderBy: $orderBy, orderDirection: $orderDirection, first: $first, skip: $skip){
        id
        createdAtTimestamp
        createdAtBlockNumber
        token0{
            id
            symbol
            name
            decimals
            totalSupply
            volume
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            poolCount
            totalValueLocked
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            derivedETH
        }
        token1{
            id
            symbol
            name
            decimals
            totalSupply
            volume
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            poolCount
            totalValueLocked
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            derivedETH
        }
        feeTier
        liquidity
        sqrtPrice
        feeGrowthGlobal0X128
        feeGrowthGlobal1X128
        token0Price
        token1Price
        tick
        observationIndex
        volumeToken0
        volumeToken1
        volumeUSD
        untrackedVolumeUSD
        feesUSD
        txCount
        collectedFeesToken0
        collectedFeesToken1
        collectedFeesUSD
        totalValueLockedToken0
        totalValueLockedToken1
        totalValueLockedETH
        totalValueLockedUSD
        totalValueLockedUSDUntracked
        liquidityProviderCount
        poolHourData{
            id
            periodStartUnix
            liquidity
            sqrtPrice
            token0Price
            token1Price
            tick
            feeGrowthGlobal0X128
            feeGrowthGlobal1X128
            tvlUSD
            volumeToken0
            volumeToken1
            volumeUSD
            feesUSD
            txCount
            open
            high
            low
            close
        }
        poolDayData{
            id
            date
            liquidity
            sqrtPrice
            token0Price
            token1Price
            tick
            feeGrowthGlobal0X128
            feeGrowthGlobal1X128
            tvlUSD
            volumeToken0
            volumeToken1
            volumeUSD
            feesUSD
            txCount
            open
            high
            low
            close
        }
        mints{
            id
            timestamp
            owner
            sender
            origin
            amount
            amount0
            amount1
            amountUSD
            tickLower
            tickUpper
            logIndex
        }
        burns{
            id
            timestamp
            owner
            origin
            amount
            amount0
            amount1
            amountUSD
            tickLower
            tickUpper
            logIndex
        }
        swaps{
            id
            timestamp
            sender
            recipient
            origin
            amount0
            amount1
            amountUSD
            sqrtPriceX96
            tick
            logIndex
        }
        collects{
            id
            timestamp
            owner
            amount0
            amount1
            amountUSD
            tickLower
            tickUpper
            logIndex
        }
        ticks{
            id
            poolAddress
            tickIdx
            liquidityGross
            liquidityNet
            price0
            price1
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            createdAtTimestamp
            createdAtBlockNumber
            liquidityProviderCount
            feeGrowthOutside0X128
            feeGrowthOutside1X128
        }
    }
}