query positionSnapshot($id: ID!, $block: Block_height){
    positionSnapshot(id: $id, block: $block){
        id
        owner
        pool{
            id
            createdAtTimestamp
            createdAtBlockNumber
            feeTier
            liquidity
            sqrtPrice
            feeGrowthGlobal0X128
            feeGrowthGlobal1X128
            token0Price
            token1Price
            tick
            observationIndex
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            totalValueLockedToken0
            totalValueLockedToken1
            totalValueLockedETH
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            liquidityProviderCount
        }
        position{
            id
            owner
            liquidity
            depositedToken0
            depositedToken1
            withdrawnToken0
            withdrawnToken1
            collectedToken0
            collectedToken1
            collectedFeesToken0
            collectedFeesToken1
            amountDepositedUSD
            amountWithdrawnUSD
            amountCollectedUSD
            feeGrowthInside0LastX128
            feeGrowthInside1LastX128
        }
        blockNumber
        timestamp
        liquidity
        depositedToken0
        depositedToken1
        withdrawnToken0
        withdrawnToken1
        collectedFeesToken0
        collectedFeesToken1
        transaction{
            id
            blockNumber
            timestamp
            gasUsed
            gasPrice
        }
        feeGrowthInside0LastX128
        feeGrowthInside1LastX128
    }
}