query positions($block: Block_height, $orderBy: Position_orderBy, $orderDirection: OrderDirection, $first: Int, $skip: Int){
    positions(block: $block, orderBy: $orderBy, orderDirection: $orderDirection, first: $first, skip: $skip){
        id
        owner
        pool{
            id
            createdAtTimestamp
            createdAtBlockNumber
            feeTier
            liquidity
            sqrtPrice
            feeGrowthGlobal0X128
            feeGrowthGlobal1X128
            token0Price
            token1Price
            tick
            observationIndex
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            totalValueLockedToken0
            totalValueLockedToken1
            totalValueLockedETH
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            liquidityProviderCount
        }
        token0{
            id
            symbol
            name
            decimals
            totalSupply
            volume
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            poolCount
            totalValueLocked
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            derivedETH
        }
        token1{
            id
            symbol
            name
            decimals
            totalSupply
            volume
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            poolCount
            totalValueLocked
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            derivedETH
        }
        tickLower{
            id
            poolAddress
            tickIdx
            liquidityGross
            liquidityNet
            price0
            price1
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            createdAtTimestamp
            createdAtBlockNumber
            liquidityProviderCount
            feeGrowthOutside0X128
            feeGrowthOutside1X128
        }
        tickUpper{
            id
            poolAddress
            tickIdx
            liquidityGross
            liquidityNet
            price0
            price1
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            createdAtTimestamp
            createdAtBlockNumber
            liquidityProviderCount
            feeGrowthOutside0X128
            feeGrowthOutside1X128
        }
        liquidity
        depositedToken0
        depositedToken1
        withdrawnToken0
        withdrawnToken1
        collectedToken0
        collectedToken1
        collectedFeesToken0
        collectedFeesToken1
        amountDepositedUSD
        amountWithdrawnUSD
        amountCollectedUSD
        transaction{
            id
            blockNumber
            timestamp
            gasUsed
            gasPrice
        }
        feeGrowthInside0LastX128
        feeGrowthInside1LastX128
        increaseEvents{
            id
            tokenID
            amount0
            amount1
            timeStamp
        }
        decreaseEvents{
            id
            tokenID
            amount0
            amount1
            timeStamp
        }
    }
}