query tickDayDatas($block: Block_height, $where: TickDayData_filter, $orderBy: TickDayData_orderBy, $orderDirection: OrderDirection, $first: Int, $skip: Int){
    tickDayDatas(block: $block, where: $where, orderBy: $orderBy, orderDirection: $orderDirection, first: $first, skip: $skip){
        id
        date
        pool{
            id
            createdAtTimestamp
            createdAtBlockNumber
            feeTier
            liquidity
            sqrtPrice
            feeGrowthGlobal0X128
            feeGrowthGlobal1X128
            token0Price
            token1Price
            tick
            observationIndex
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            totalValueLockedToken0
            totalValueLockedToken1
            totalValueLockedETH
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            liquidityProviderCount
        }
        tick{
            id
            poolAddress
            tickIdx
            liquidityGross
            liquidityNet
            price0
            price1
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            createdAtTimestamp
            createdAtBlockNumber
            liquidityProviderCount
            feeGrowthOutside0X128
            feeGrowthOutside1X128
        }
        liquidityGross
        liquidityNet
        volumeToken0
        volumeToken1
        volumeUSD
        feesUSD
        feeGrowthOutside0X128
        feeGrowthOutside1X128
    }
}