query tick($id: ID!, $block: Block_height){
    tick(id: $id, block: $block){
        id
        poolAddress
        tickIdx
        pool{
            id
            createdAtTimestamp
            createdAtBlockNumber
            feeTier
            liquidity
            sqrtPrice
            feeGrowthGlobal0X128
            feeGrowthGlobal1X128
            token0Price
            token1Price
            tick
            observationIndex
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            collectedFeesToken0
            collectedFeesToken1
            collectedFeesUSD
            totalValueLockedToken0
            totalValueLockedToken1
            totalValueLockedETH
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            liquidityProviderCount
        }
        liquidityGross
        liquidityNet
        price0
        price1
        volumeToken0
        volumeToken1
        volumeUSD
        untrackedVolumeUSD
        feesUSD
        collectedFeesToken0
        collectedFeesToken1
        collectedFeesUSD
        createdAtTimestamp
        createdAtBlockNumber
        liquidityProviderCount
        feeGrowthOutside0X128
        feeGrowthOutside1X128
    }
}