query tokenDayData($id: ID!, $block: Block_height){
    tokenDayData(id: $id, block: $block){
        id
        date
        token{
            id
            symbol
            name
            decimals
            totalSupply
            volume
            volumeUSD
            untrackedVolumeUSD
            feesUSD
            txCount
            poolCount
            totalValueLocked
            totalValueLockedUSD
            totalValueLockedUSDUntracked
            derivedETH
        }
        volume
        volumeUSD
        untrackedVolumeUSD
        totalValueLocked
        totalValueLockedUSD
        priceUSD
        feesUSD
        open
        high
        low
        close
    }
}