query transaction($id: ID!, $block: Block_height){
    transaction(id: $id, block: $block){
        id
        blockNumber
        timestamp
        gasUsed
        gasPrice
        mints{
            id
            timestamp
            owner
            sender
            origin
            amount
            amount0
            amount1
            amountUSD
            tickLower
            tickUpper
            logIndex
        }
        burns{
            id
            timestamp
            owner
            origin
            amount
            amount0
            amount1
            amountUSD
            tickLower
            tickUpper
            logIndex
        }
        swaps{
            id
            timestamp
            sender
            recipient
            origin
            amount0
            amount1
            amountUSD
            sqrtPriceX96
            tick
            logIndex
        }
        flashed{
            id
            timestamp
            sender
            recipient
            amount0
            amount1
            amountUSD
            amount0Paid
            amount1Paid
            logIndex
        }
        collects{
            id
            timestamp
            owner
            amount0
            amount1
            amountUSD
            tickLower
            tickUpper
            logIndex
        }
    }
}