query uniswapDayDatas($block: Block_height, $where: UniswapDayData_filter, $orderBy: UniswapDayData_orderBy, $orderDirection: OrderDirection, $first: Int, $skip: Int){
    uniswapDayDatas(block: $block, where: $where, orderBy: $orderBy, orderDirection: $orderDirection, first: $first, skip: $skip){
        id
        date
        volumeETH
        volumeUSD
        volumeUSDUntracked
        feesUSD
        txCount
        tvlUSD
    }
}